---
- hosts: all
  become: yes
  tasks:
  - name: Installing apache2 package
    apt:
      name: apache2
      state: present
    notify: 
      Restart Service
  - name: Install lamp dependendies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php  
      - libapache2-mod-php
      - php-mysql
    notify: 
      Restart Service
  handlers:
  - name: Restart Service
    systemd:
      name: apache2
      enabled: yes
      state: restarted

          