---
- hosts: all
  become: yes
  tasks: 
  - name: Checking Connectivity
    ping:
  - name: Uninstalling Git package
    apt:
      name: git
      state: absent
      update_cache: yes
  - name: Uninstalling Tree package
    apt:
      name: tree
      state: absent      
  